---
# base path format: "foo\\bar\\test data"
base_path: "C:\\Users\\dkane\\OneDrive - Presto Engineering\\Documents\\AMF\\56G PD Quals\\Lot #2\\test data"
#pkg: [TO39, SM]

#sn_to_skip:
#  TO39: &to39_sn_to_skip [110, 111]
#  SM: &sm_sn_to_skip []
    
params:
  TO39:
    T_ambient (C): 
      hilim: inf
      lolim: -inf
      sn_to_skip: &to39_sn_to_skip [110, 111] # sn to ignore for particular param
      #sn_to_skip: &to39_sn_to_skip [] # sn to ignore for particular param
      axis_type: linear # option are linear and log
    Dark Current (A) @ -3V:
      hilim: 50
      lolim: -inf 
      sn_to_skip: *to39_sn_to_skip
      axis_type: log
    Resistance (ohm) @ 1V:
      hilim: 20
      lolim: -inf
      sn_to_skip: *to39_sn_to_skip
      axis_type: linear
  SM:
    T_ambient (C): 
      hilim: inf
      lolim: -inf
      sn_to_skip: &sm_sn_to_skip [308237-25] # sn to ignore for particular param
      #sn_to_skip: &sm_sn_to_skip [] # sn to ignore for particular param
      axis_type: linear
    Dark Current (A) @ -3V:
      hilim: 50
      lolim: -inf
      sn_to_skip: *sm_sn_to_skip
      axis_type: log
    Resistance (ohm) @ 1V:
      hilim: 20
      lolim: -inf    
      sn_to_skip: *sm_sn_to_skip
      axis_type: linear
    Photocurrent (A) @ 1530nm: 
      hilim: inf
      lolim: -50
      sn_to_skip: *sm_sn_to_skip # sn to ignore for particular param
      axis_type: log
    Photocurrent (A) @ 1550nm:
      hilim: inf
      lolim: -50 
      sn_to_skip: *sm_sn_to_skip
      axis_type: log
    Photocurrent (A) @ 1570nm:
      hilim: inf
      lolim: -50    
      sn_to_skip: *sm_sn_to_skip
      axis_type: log